---
fabric_name: ATD_FABRIC

# OOB Management network default gateway
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# underlay_rfc5549: true
# overlay_mlag_rfc5549: true

underlay_routing_protocol: ebgp

# Optional, enable multicast features
# underlay_multicast: true
# evpn_multicast: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

l3_edge:
  p2p_links_ip_pools:
    BORDER_IP: 172.16.200.0/24
  p2p_links:
    - id: 1
      ip_pool: BORDER_IP
      nodes: [s1-brdr1, s2-brdr1]
      interfaces: [Ethernet4, Ethernet4]
      as: [65103, 65203]
      descriptions: ["s1 Border Leaf 1", "s2 Border Leaf 1"]
      include_in_underlay_protocol: true
    - id: 2
      ip_pool: BORDER_IP
      nodes: [s1-brdr2, s2-brdr2]
      interfaces: [Ethernet4, Ethernet4]
      as: [65103, 65203]
      descriptions: ["s1 Border Leaf 1", "s2 Border Leaf 1"]
      include_in_underlay_protocol: true



#### Override for vEOS Lab Caveats ####

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# atd parameters
mgmt_interface: Management0
name_servers:
  - 192.168.2.1
  - 8.8.8.8
dns_domain: atd.lab

# act parameters
# mgmt_interface: Management1
# name_servers:
#   - 10.255.0.2
# ntp:
#   servers:
#     - name: 0.pool.ntp.org
#       local_interface: Management1
#     - name: 1.pool.ntp.org
#       local_interface: Management1
#   authenticate: false
# cvp_instance_ip: 192.168.0.5
# custom_structured_configuration_daemon_terminattr:
#   cvauth:
#     method: "token"
#     token_file: "/tmp/token"
# local_users:
#   admin:
#     privilege: 15
#     role: network-admin
#     sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"
#   cvpadmin:
#     privilege: 15
#     role: network-admin
#     sha512_password: "$6$qI16FDuEyTyahgyH$su2QQ4zgkOLu1269G7PM1pdM0xHV0AeBJ6nSUzCcGeTrIqCJYpEK8t/KKDtUy6Q8YyUGoYe2ZFPNYqprB482b0"
#   ansible:
#     privilege: 15
#     role: network-admin
#     sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

