---
- name: Configure ZTP/DHCP service on CloudVision
  hosts: cv_ztp
  gather_facts: true
  connection: local
  collections:
    - arista.cvp
  tasks:
  - name: 'Execute ZTP configuration role'
    import_role:
      name: arista.cvp.dhcp_configuration

